language: python
sudo: enabled
dist: xenial
group: edge

python:
  - "3.7"

services:
  - docker

before_script:
  - docker build -t selenium:lims $TRAVIS_BUILD_DIR/ --no-cache

script:
  - docker run --shm-size=2g -v $TRAVIS_BUILD_DIR:/1lims-automation selenium:lims bash -c "./run.sh"
