name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:

        test_cases: ["ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test001_edit_order_number_with_save_cancel_btn_0_save_btn",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test001_edit_order_number_with_save_cancel_btn_1_cancel",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test002_update_contact_with_save_cancel_btn_0_save_btn",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test002_update_contact_with_save_cancel_btn_1_cancel",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test003_cancel_button_edit_departments_0_save_btn",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test003_cancel_button_edit_departments_1_cancel",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test004_archive_main_order",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test005_restore_archived_orders",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test006_delete_main_order",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test007_order_search_0_True",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test007_order_search_1_False",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test008_duplicate_main_order"
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test009_export_order_sheet",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test010_user_can_add_suborder",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test011_duplicate_many_orders",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test012_update_first_order_material_type_0_save_btn",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test012_update_first_order_material_type_1_cancel",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test013_filter_by_any_fields_0_materialType",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test013_filter_by_any_fields_1_article",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test013_filter_by_any_fields_2_testPlans",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test013_filter_by_any_fields_3_testUnit",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test013_filter_by_any_fields_4_lastModifiedUser",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test013_filter_by_any_fields_5_analysis",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test014_filter_by_order_No",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test015_filter_by_Status",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test016_filter_by_analysis_result",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test017_filter_by_contact",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test018_filter_by_department",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test019_filter_by_date_0_testDate",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test019_filter_by_date_1_shipmentDate",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test019_filter_by_date_2_createdAt",
                     "ui_testing/testcases/basic_tests/test06_orders.py:OrdersTestCases.test020_validate_order_test_unit_test_plan"]



    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run:  pip3 install -r requirements.txt
      - name: Execute test case
        run: |
          export PYTHONPATH='$PYTHONPATH:./'
          script -e -c $'xvfb-run -a ~/.local/bin/nosetests-3.4 -vs --nologcapture --tc-file=config.ini ${{ matrix.test_cases }}'

